// LINK_ACTIONS
export const GET_LINK_ANALYTICS = 'GET_LINK_ANALYTICS';
export const RESET_CURRENT_LINK = 'RESET_CURRENT_LINK';
export const CREATE_LINK = 'CREATE_LINK';

// SNACKBAR_ACTIONS
export const DISPLAY_SNACKBAR = 'DISPLAY_SNACKBAR';
export const HANDLE_CLOSE = 'HANDLE_CLOSE';

// ERROR_ACTIONS
export const RESET_ERRORS = 'RESET_ERRORS';
